version: "3"

services:
  matter:
    container_name: mattermost-preview
    image: mattermost/mattermost-preview
    ports:
      - 8065:8065
    networks:
      - dummy-net
    environment:
      - USERNAME={{ secrets.auth_usr }}
      - PASSWORD={{ secrets.auth_pwd }}
    volumes:
      - /home/linodeuser/www/:/usr/share/nginx/html

networks:
  dummy-net: