version: "3"

services:
  app:
    image: ngnix:latest
    ports:
      - 800:80
    networks:
      - dummy-net
    volumes:
      - /home/linodeuser/www/:/usr/share/nginx/html

networks:
  dummy-net:

volumes:
  portainer: